export const en = {
    translation: {
        "all article": "All article",
        "stared article": "Stared article",
        "add subscription": "Add subscription",
        "rss url": "RSS url",
        "folder": "Folder",
        "rssUrlInputPlaceholder": "RSS url here",
        "folderDropdownPlaceholder": "Folder here",
        "langDropdownPlaceholder": "Select the language",
        "add": "Add",
        "cancel": "Cancel",
        "theme": "Theme",
        "filter": "Filter",
        "layout": "Layout",
        "always": "Always",
        "unread only": "Unread only",
        "never": "Never",
        "auto": "Auto",
        "log off": "Log off",
        "publish at": "Publish at",
        "article setting": "Article setting",
        "tight": "Tight",
        "normal": "Normal",
        "wide": "Wide",
        "font size": "Font size",
        "line space": "Line space",
        "lang": "Language",
    },
    settings: {
        "settings": "Settings",
        "general": "General",
        "account": "Account",
        "subscription": "Subscription",
        "reading preference": "Reading preference",
        "user interface": "User interface",
        "about": "About",
    },
    viewSettings: {
        "magazine view": "Magazine view",
        "split view": "Split view",
        "list view": "List view",
        "thumbnail display": "Thumbnail display",
        "feeditem style": "Feeditem style",
        "cover in left": "Cover in left",
        "cover in right": "Cover in right",
        "social media": "Social media",
    },
    articleAction: {
        "read": "Read",
        "star": "Star",
        "share": "Share",
        "mark above as read": "Mark above as read",
    },
    lang: {
        "zh": "Chinese(Simple)",
        "en": "English",
    },
};
