export const zh = {
    translation: {
        "all article": "全部文章",
        "stared article": "星标文章",
        "add subscription": "添加订阅源",
        "rss url": "RSS 地址",
        "folder": "文件夹",
        "rssUrlInputPlaceholder": "请输入 RSS 地址",
        "folderDropdownPlaceholder": "请选择要添加到的文件夹",
        "add": "添加",
        "cancel": "取消",
        "theme": "主题",
        "filter": "过滤",
        "layout": "布局",
        "always": "总是",
        "unread only": "仅未读",
        "never": "从不",
        "auto": "自动",
        "log off": "退出登录",
        "publish at": "发布于",
        "article setting": "文章设置",
        "tight": "紧凑",
        "normal": "正常",
        "wide": "宽松",
        "font size": "字体大小",
        "line space": "行间距",
    },
    settings: {
        "settings": "设置",
        "general": "常规",
        "account": "账号",
        "subscription": "订阅源",
        "reading preference": "阅读",
        "user interface": "界面",
        "about": "关于",
    },
    viewSettings: {
        "magazine view": "杂志",
        "split view": "多列",
        "list view": "单行",
        "thumbnail display": "缩略图显示",
        "feeditem style": "文章条目样式",
        "cover in left": "图片在左",
        "cover in right": "图片在右",
        "social media": "社交媒体",
    },
    articleAction: {
        "read": "已读",
        "star": "收藏",
        "share": "分享",
        "mark above as read": "将以上标记为已读",
    }
};
